---
- hosts: server
  become: true
  vars:
    nginx_install_dir: "/tmp/{{ nginx_version }}"
    nginx_sbin_path: "/usr/sbin/nginx"
    nginx_conf_path: "/etc/nginx/nginx.conf"
    nginx_custom_modules: "--with-http_auth_request_module"
    nginx_listen_port: 8080

  tasks:
  - name: making folder for site
    become: true
    file:
      path: /opt/www
      state: directory
      owner: root
      mode: 0777

  - name: install packages via yum
    become: true
    yum:
      name: "{{item}}"
      state: present
    loop:
      - mc
      - nano
      - yum-utils

  - name: install epel repository
    yum:
      name: epel-release
      state: present
    tags:
      - epel-package
      - packages

  - name: Install nginx from epel via yum
    yum:
      name: nginx
      state: latest
    notify:
      - restart nginx
    tags:
      - nginx-package
      - packages

  - name: Create custom config using jinja2
    template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
    notify:
        - reload nginx
    tags:
        - nginx-configuration

  - name: copy default page index.html
    copy:
      src: index.html
      dest: /opt/www/index.html
      owner: root
      group: root
      mode: '0777'
    become: true
    notify: reload nginx

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes

  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded


